# Site settings
title: chenkaiwei的博客
email: chenkaiwei.1988@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
weibo_username: _舷_
github_username:  chenkaiwei

# Build settings
markdown: kramdown
excerpt_separator: <!--@excerpt-end-->

# Navigations
navigations:
  - title: 首页
    class: fa fa-list-ul
    href: /
  - title: 时间线
    class: fa fa-tags
    href: /archive/
  - title: 分类
    class: fa fa-user
    href: /categories/
  - title: 自述
    class: fa fa-list-ul
    href: /about